In [1]:
import pandas as pd

# Path to your pickle file
file_path = 'readability_results.pkl'

# Read the DataFrame from the pickle file
df = pd.read_pickle(file_path)

df

,term,formal_definition,simplified_explanation,formal_fk_grade,formal_flesch_ease,formal_smog,formal_gunning_fog,formal_dale_chall,formal_text_standard,formal_word_count,...,simplified_type_token_ratio,simplified_long_word_percentage,improvement_fk_grade,improvement_flesch_ease,improvement_smog,improvement_gunning_fog,improvement_dale_chall,improvement_word_length,improvement_syllables,improvement_long_word_percentage
0,biomarker testing,biomarker testing is A laboratory method that ...,"Okay, I've got it! Here's my attempt to explai...",11.5,55.58,12.3,13.60,9.30,11th and 12th grade,137,...,0.675497,1.986755,3.3,19.25,5.1,4.00,2.28,0.339779,0.222507,7.502296
1,biopsy,biopsy is The removal of cells or tissues for ...,"Sure! Here's my attempt to explain the term ""b...",10.2,53.51,12.5,11.61,8.69,8th and 9th grade,126,...,0.617647,3.676471,-1.2,13.10,3.0,-1.65,1.85,0.360644,0.230392,9.021942
2,chromosome,chromosome is Part of a cell that contains gen...,"Sure, I'd be happy to help! Here's my explanat...",7.2,61.33,0.0,10.00,12.03,7th and 8th grade,23,...,0.582192,15.068493,-1.8,0.74,-13.0,-0.29,4.18,0.388922,0.101251,-2.025015
3,clinical trial,clinical trial is A type of research study tha...,Certainly! Here's my attempt to explain the te...,7.7,60.01,10.5,10.40,10.70,10th and 11th grade,40,...,0.614815,8.148148,-2.4,4.63,-1.1,-0.67,3.20,0.496296,0.160185,4.351852
4,fertility,fertility is The ability to produce children.,"Sure, I'd be happy to help! Here's my explanat...",8.0,48.47,0.0,9.07,9.20,7th and 8th grade,7,...,0.654971,8.187135,-2.1,10.76,-11.2,-2.17,1.24,0.291562,0.331662,6.098580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,intravenous urogram,intravenous urogram is An x-ray image of the k...,"Sure, I'd be happy to help! Here's my attempt ...",9.4,61.06,11.2,10.88,10.33,10th and 11th grade,110,...,0.552995,3.225806,1.8,15.39,3.0,1.74,3.34,0.480855,0.184918,5.865103
370,stage 0 transitional cell carcinoma in situ of...,stage 0 transitional cell carcinoma in situ of...,"Okay! Let me explain ""stage 0 transitional cel...",9.8,60.04,10.4,10.29,8.31,9th and 10th grade,107,...,0.530864,3.292181,2.7,17.73,2.4,1.61,1.15,0.344064,0.259375,4.184454
371,vacuum-assisted core biopsy,vacuum-assisted core biopsy is A procedure in ...,"Okay! Here's my attempt to explain ""vacuum-ass...",7.3,66.33,9.6,8.76,8.84,8th and 9th grade,101,...,0.656977,3.488372,-1.0,2.88,1.1,0.14,1.76,0.657034,0.208266,5.422519
372,vasoactive intestinal peptide,vasoactive intestinal peptide is A hormone fou...,Okay! Let me explain what vasoactive intestina...,8.4,58.28,9.3,8.28,9.75,8th and 9th grade,92,...,0.604938,9.259259,-3.1,-2.70,-2.6,-3.82,1.30,0.017848,0.040660,-1.650564
373,white blood cell,white blood cell is A type of blood cell that ...,"Sure, I'd be happy to explain the term ""white ...",6.4,74.08,10.6,10.08,9.12,8th and 9th grade,121,...,0.592040,6.467662,-0.3,4.81,1.0,0.97,2.46,0.195798,0.007771,3.449694

In [9]:
def txt_to_dict(file_path):
    data_dict = {}
    with open(file_path, 'r') as file:
        lines = file.readlines()
        for i in range(0, len(lines) - 1, 2):
            key = lines[i].strip()    # Odd line are key
            value = lines[i + 1].strip()  # Even line are value
            data_dict[key] = value

    return data_dict


txt_file_path = 'formaldef.txt' 
formaldic = txt_to_dict(txt_file_path)
len(formaldic)

res={}
for k,v in formaldic.items():
    res[k.split('Listen to pronunciation')[0].split('(')[0]]=v
formaldic=res
import csv

def csv_to_dict(file_path):
    data_dict = {}
    with open(file_path, mode='r', newline='') as csvfile:
        reader = csv.reader(csvfile)
        next(reader)
        for row in reader:
            if len(row) >= 3: 
                key, value = row[1].strip(), row[2].strip()
                data_dict[key] = value
    return data_dict

csv_file_path = 'easydef.csv' 
easydic = csv_to_dict(csv_file_path)
csv_file_path = 'easydef2.csv' 
easydic2 = csv_to_dict(csv_file_path)

easydic=easydic|easydic2
len(easydic)

# Import pandas
import pandas as pd

# Create a DataFrame instead of a list
data_list = []
for k in easydic.keys():
    if k in formaldic:
        data_list.append([k, easydic[k]])

# Convert to DataFrame with appropriate column names
data = pd.DataFrame(data_list, columns=['term', 'easy_definition'])

# Display the first few rows
data.head(2)

                term                                    easy_definition
0  biomarker testing  A lab test of any molecule in your body that c...
1             biopsy  A procedure that removes fluid or tissue sampl...

In [10]:
joined_df = pd.merge(df, data, on='term', how='inner')
joined_df

,term,formal_definition,simplified_explanation,formal_fk_grade,formal_flesch_ease,formal_smog,formal_gunning_fog,formal_dale_chall,formal_text_standard,formal_word_count,...,simplified_long_word_percentage,improvement_fk_grade,improvement_flesch_ease,improvement_smog,improvement_gunning_fog,improvement_dale_chall,improvement_word_length,improvement_syllables,improvement_long_word_percentage,easy_definition
0,biomarker testing,biomarker testing is A laboratory method that ...,"Okay, I've got it! Here's my attempt to explai...",11.5,55.58,12.3,13.60,9.30,11th and 12th grade,137,...,1.986755,3.3,19.25,5.1,4.00,2.28,0.339779,0.222507,7.502296,A lab test of any molecule in your body that c...
1,biopsy,biopsy is The removal of cells or tissues for ...,"Sure! Here's my attempt to explain the term ""b...",10.2,53.51,12.5,11.61,8.69,8th and 9th grade,126,...,3.676471,-1.2,13.10,3.0,-1.65,1.85,0.360644,0.230392,9.021942,A procedure that removes fluid or tissue sampl...
2,chromosome,chromosome is Part of a cell that contains gen...,"Sure, I'd be happy to help! Here's my explanat...",7.2,61.33,0.0,10.00,12.03,7th and 8th grade,23,...,15.068493,-1.8,0.74,-13.0,-0.29,4.18,0.388922,0.101251,-2.025015,Part of a cell that contains genetic informati...
3,clinical trial,clinical trial is A type of research study tha...,Certainly! Here's my attempt to explain the te...,7.7,60.01,10.5,10.40,10.70,10th and 11th grade,40,...,8.148148,-2.4,4.63,-1.1,-0.67,3.20,0.496296,0.160185,4.351852,A type of research that assesses health tests ...
4,fertility,fertility is The ability to produce children.,"Sure, I'd be happy to help! Here's my explanat...",8.0,48.47,0.0,9.07,9.20,7th and 8th grade,7,...,8.187135,-2.1,10.76,-11.2,-2.17,1.24,0.291562,0.331662,6.098580,The ability to produce children.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,intravenous urogram,intravenous urogram is An x-ray image of the k...,"Sure, I'd be happy to help! Here's my attempt ...",9.4,61.06,11.2,10.88,10.33,10th and 11th grade,110,...,3.225806,1.8,15.39,3.0,1.74,3.34,0.480855,0.184918,5.865103,"An x-ray image of the kidneys, ureters, and bl..."
370,stage 0 transitional cell carcinoma in situ of...,stage 0 transitional cell carcinoma in situ of...,"Okay! Let me explain ""stage 0 transitional cel...",9.8,60.04,10.4,10.29,8.31,9th and 10th grade,107,...,3.292181,2.7,17.73,2.4,1.61,1.15,0.344064,0.259375,4.184454,Abnormal cells are found in tissue lining the ...
371,vacuum-assisted core biopsy,vacuum-assisted core biopsy is A procedure in ...,"Okay! Here's my attempt to explain ""vacuum-ass...",7.3,66.33,9.6,8.76,8.84,8th and 9th grade,101,...,3.488372,-1.0,2.88,1.1,0.14,1.76,0.657034,0.208266,5.422519,A procedure in which a small sample of tissue ...
372,vasoactive intestinal peptide,vasoactive intestinal peptide is A hormone fou...,Okay! Let me explain what vasoactive intestina...,8.4,58.28,9.3,8.28,9.75,8th and 9th grade,92,...,9.259259,-3.1,-2.70,-2.6,-3.82,1.30,0.017848,0.040660,-1.650564,"A hormone found in the pancreas, intestine, an..."
373,white blood cell,white blood cell is A type of blood cell that ...,"Sure, I'd be happy to explain the term ""white ...",6.4,74.08,10.6,10.08,9.12,8th and 9th grade,121,...,6.467662,-0.3,4.81,1.0,0.97,2.46,0.195798,0.007771,3.449694,A type of blood cell that is made in the bone ...

In [7]:
import numpy as np
np.mean(df.improvement_fk_grade),np.mean(df.improvement_flesch_ease)

(0.3270053475935829, 8.267192513368984)

In [13]:
joined_df.to_csv('out.csv', index=False)